// src/lib/mockData.ts

export const currentUser = {
  id: '1',
  name: 'Maria Santos',
  email: 'maria.santos@email.com',
  avatar: 'MS',
  role: 'Patient',
  joinedDate: '2024-01-15',
  condition: 'Hypertension, Type 2 Diabetes',
  doctor: 'Dr. Jose Reyes',
  phone: '+63 912 345 6789',
}

export const medications = [
  {
    id: '1',
    name: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    times: ['08:00', '20:00'],
    category: 'Antidiabetic',
    color: 'blue',
    stock: 45,
    totalStock: 60,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2024-01-15',
    endDate: '2024-07-15',
    instructions: 'Take with food',
    status: 'active',
    refillDate: '2024-06-01',
    shape: 'oval',
    pillColor: '#4A90D9',
  },
  {
    id: '2',
    name: 'Amlodipine',
    dosage: '5mg',
    frequency: 'Once daily',
    times: ['08:00'],
    category: 'Calcium Channel Blocker',
    color: 'teal',
    stock: 12,
    totalStock: 30,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2024-02-01',
    endDate: '2024-08-01',
    instructions: 'Take at the same time each day',
    status: 'active',
    refillDate: '2024-05-25',
    shape: 'round',
    pillColor: '#14B8A6',
  },
  {
    id: '3',
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily',
    times: ['21:00'],
    category: 'Statin',
    color: 'purple',
    stock: 28,
    totalStock: 30,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2024-01-20',
    endDate: '2024-07-20',
    instructions: 'Take in the evening',
    status: 'active',
    refillDate: '2024-06-10',
    shape: 'oval',
    pillColor: '#8B5CF6',
  },
  {
    id: '4',
    name: 'Aspirin',
    dosage: '81mg',
    frequency: 'Once daily',
    times: ['08:00'],
    category: 'Antiplatelet',
    color: 'orange',
    stock: 3,
    totalStock: 30,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2024-03-01',
    endDate: '2024-09-01',
    instructions: 'Take with a full glass of water',
    status: 'low-stock',
    refillDate: '2024-05-20',
    shape: 'round',
    pillColor: '#F97316',
  },
  {
    id: '5',
    name: 'Vitamin D3',
    dosage: '1000 IU',
    frequency: 'Once daily',
    times: ['12:00'],
    category: 'Supplement',
    color: 'yellow',
    stock: 60,
    totalStock: 90,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2024-01-15',
    endDate: '2024-12-31',
    instructions: 'Take with a meal',
    status: 'active',
    refillDate: '2024-08-01',
    shape: 'softgel',
    pillColor: '#EAB308',
  },
  {
    id: '6',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    times: ['08:00'],
    category: 'ACE Inhibitor',
    color: 'red',
    stock: 0,
    totalStock: 30,
    prescribedBy: 'Dr. Jose Reyes',
    startDate: '2023-12-01',
    endDate: '2024-05-01',
    instructions: 'Avoid potassium supplements',
    status: 'expired',
    refillDate: '2024-04-15',
    shape: 'oval',
    pillColor: '#EF4444',
  },
]

export const todayReminders = [
  {
    id: '1',
    medicationId: '1',
    medicationName: 'Metformin 500mg',
    time: '08:00',
    status: 'taken',
    takenAt: '08:04',
    pillColor: '#4A90D9',
  },
  {
    id: '2',
    medicationId: '2',
    medicationName: 'Amlodipine 5mg',
    time: '08:00',
    status: 'taken',
    takenAt: '08:04',
    pillColor: '#14B8A6',
  },
  {
    id: '3',
    medicationId: '4',
    medicationName: 'Aspirin 81mg',
    time: '08:00',
    status: 'missed',
    takenAt: null,
    pillColor: '#F97316',
  },
  {
    id: '4',
    medicationId: '5',
    medicationName: 'Vitamin D3 1000 IU',
    time: '12:00',
    status: 'taken',
    takenAt: '12:10',
    pillColor: '#EAB308',
  },
  {
    id: '5',
    medicationId: '1',
    medicationName: 'Metformin 500mg',
    time: '20:00',
    status: 'upcoming',
    takenAt: null,
    pillColor: '#4A90D9',
  },
  {
    id: '6',
    medicationId: '3',
    medicationName: 'Atorvastatin 20mg',
    time: '21:00',
    status: 'upcoming',
    takenAt: null,
    pillColor: '#8B5CF6',
  },
]

export const medicationHistory = [
  { date: '2024-05-16', taken: 5, missed: 1, scheduled: 6 },
  { date: '2024-05-15', taken: 6, missed: 0, scheduled: 6 },
  { date: '2024-05-14', taken: 5, missed: 1, scheduled: 6 },
  { date: '2024-05-13', taken: 6, missed: 0, scheduled: 6 },
  { date: '2024-05-12', taken: 4, missed: 2, scheduled: 6 },
  { date: '2024-05-11', taken: 6, missed: 0, scheduled: 6 },
  { date: '2024-05-10', taken: 6, missed: 0, scheduled: 6 },
]

export const adherenceData = [
  { month: 'Nov', adherence: 82 },
  { month: 'Dec', adherence: 88 },
  { month: 'Jan', adherence: 91 },
  { month: 'Feb', adherence: 85 },
  { month: 'Mar', adherence: 93 },
  { month: 'Apr', adherence: 89 },
  { month: 'May', adherence: 87 },
]

export const weeklyAdherence = [
  { day: 'Mon', taken: 6, missed: 0 },
  { day: 'Tue', taken: 5, missed: 1 },
  { day: 'Wed', taken: 6, missed: 0 },
  { day: 'Thu', taken: 4, missed: 2 },
  { day: 'Fri', taken: 6, missed: 0 },
  { day: 'Sat', taken: 6, missed: 0 },
  { day: 'Sun', taken: 5, missed: 1 },
]

export const detailedHistory = [
  {
    id: '1',
    date: '2024-05-16',
    time: '08:04',
    medication: 'Metformin 500mg',
    scheduledTime: '08:00',
    status: 'taken',
    note: '',
    pillColor: '#4A90D9',
  },
  {
    id: '2',
    date: '2024-05-16',
    time: '08:04',
    medication: 'Amlodipine 5mg',
    scheduledTime: '08:00',
    status: 'taken',
    note: '',
    pillColor: '#14B8A6',
  },
  {
    id: '3',
    date: '2024-05-16',
    time: null,
    medication: 'Aspirin 81mg',
    scheduledTime: '08:00',
    status: 'missed',
    note: 'Ran out of stock',
    pillColor: '#F97316',
  },
  {
    id: '4',
    date: '2024-05-16',
    time: '12:10',
    medication: 'Vitamin D3 1000 IU',
    scheduledTime: '12:00',
    status: 'taken',
    note: '',
    pillColor: '#EAB308',
  },
  {
    id: '5',
    date: '2024-05-15',
    time: '08:01',
    medication: 'Metformin 500mg',
    scheduledTime: '08:00',
    status: 'taken',
    note: '',
    pillColor: '#4A90D9',
  },
  {
    id: '6',
    date: '2024-05-15',
    time: '08:01',
    medication: 'Amlodipine 5mg',
    scheduledTime: '08:00',
    status: 'taken',
    note: '',
    pillColor: '#14B8A6',
  },
  {
    id: '7',
    date: '2024-05-15',
    time: '08:05',
    medication: 'Aspirin 81mg',
    scheduledTime: '08:00',
    status: 'taken',
    note: '',
    pillColor: '#F97316',
  },
  {
    id: '8',
    date: '2024-05-15',
    time: '12:00',
    medication: 'Vitamin D3 1000 IU',
    scheduledTime: '12:00',
    status: 'taken',
    note: '',
    pillColor: '#EAB308',
  },
  {
    id: '9',
    date: '2024-05-15',
    time: '20:02',
    medication: 'Metformin 500mg',
    scheduledTime: '20:00',
    status: 'taken',
    note: '',
    pillColor: '#4A90D9',
  },
  {
    id: '10',
    date: '2024-05-15',
    time: '21:15',
    medication: 'Atorvastatin 20mg',
    scheduledTime: '21:00',
    status: 'late',
    note: 'Forgot until bedtime',
    pillColor: '#8B5CF6',
  },
]

export const chatMessages = [
  {
    id: '1',
    role: 'assistant' as const,
    content: "Hello Maria! 👋 I'm your Dose Alert assistant. I can help you check your medication schedule, confirm doses, or answer questions about your medications. What would you like to know?",
    timestamp: '09:00',
  },
  {
    id: '2',
    role: 'user' as const,
    content: 'What medications should I take today?',
    timestamp: '09:01',
  },
  {
    id: '3',
    role: 'assistant' as const,
    content: "Today you have 6 scheduled doses:\n\n🌅 **8:00 AM** (Morning)\n• Metformin 500mg ✅ Taken at 8:04 AM\n• Amlodipine 5mg ✅ Taken at 8:04 AM\n• Aspirin 81mg ❌ Missed\n\n☀️ **12:00 PM** (Noon)\n• Vitamin D3 1000 IU ✅ Taken at 12:10 PM\n\n🌙 **8:00 PM** (Evening)\n• Metformin 500mg ⏰ Upcoming\n\n🌃 **9:00 PM** (Night)\n• Atorvastatin 20mg ⏰ Upcoming\n\nYou have 2 upcoming doses. Don't forget!",
    timestamp: '09:01',
  },
  {
    id: '4',
    role: 'user' as const,
    content: 'Did I already take my Metformin this morning?',
    timestamp: '09:02',
  },
  {
    id: '5',
    role: 'assistant' as const,
    content: "Yes! ✅ You took your **Metformin 500mg** (morning dose) at **8:04 AM** today — just 4 minutes after your scheduled time. Great job staying on track!\n\nYour next Metformin dose is at **8:00 PM** this evening.",
    timestamp: '09:02',
  },
]

export const quickChatSuggestions = [
  "What medications should I take today?",
  "Did I take my morning pills?",
  "Which medications am I running low on?",
  "What's my adherence rate this month?",
  "When is my next dose?",
  "Show me my medication list",
]

export const notifications = [
  { id: '1', type: 'warning', message: 'Aspirin is running very low (3 pills left)', time: '10 min ago', read: false },
  { id: '2', type: 'reminder', message: 'Metformin dose at 8:00 PM in 2 hours', time: '30 min ago', read: false },
  { id: '3', type: 'success', message: 'You took all your noon medications on time!', time: '2 hours ago', read: true },
  { id: '4', type: 'info', message: 'Amlodipine refill due in 5 days', time: '1 day ago', read: true },
]